name: Deploy Next.js to Azure

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 배포

env:
  IMAGE_NAME: kyeni/front-end   # <-- Docker Hub 리포지토리

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      #태그설정
      - name: Set tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      #docker login
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (Docker Hub)
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
          docker tag  $IMAGE_NAME:${{ steps.vars.outputs.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          docker push $IMAGE_NAME:latest

      # 2️⃣ Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x


      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4️⃣ 빌드
      - name: Build Next.js app
        run: npm run build
        
      # ✅ 아티팩트
      - name: Prepare standalone artifact
        run: |
          rm -rf out-azure
          mkdir -p out-azure
          cp -r .next/standalone/* out-azure/
          mkdir -p out-azure/.next
          cp -r .next/static out-azure/.next/static
          if [ -d public ]; then cp -r public out-azure/public; fi
          # (옵션) 안전 체크: server.js 없으면 실패
          test -f out-azure/server.js || (echo "server.js not found" && exit 1)

      # 5️⃣ Azure에 배포
      - name: frontend-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontend-service  # App Service 이름
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '.'  # 루트 폴더
