name: Deploy Next.js to Azure

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 배포

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION || '20.x' }}

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4️⃣ 빌드
      - name: Build Next.js app
        run: npm run build

      # 5️⃣ Azure에 배포
      - name: frontend-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontend-service  # App Service 이름
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'  # 루트 폴더
